# Tests for get_profile()
# Uses HAK_2025 profile outputs generated by:
# casal2 -p -o profile.dat -c config.csl2 > profile.log 2> profile.err
# setup.R defines: TESTMODELS_DIR, testmodel()

library(testthat)
library(Casal2)

test_that("get_profile returns expected columns for HAK_2025/profile.log", {
  mpd <- extract.mpd(file = testmodel("HAK_2025/profile.log"), quiet = TRUE)
  prof <- get_profile(mpd)

  expect_true(is.data.frame(prof))
  expect_true(all(c("component", "parameter_values", "negative_loglikelihood", "parameter") %in% names(prof)))
  expect_true(nrow(prof) > 0L)
  expect_true(all(is.finite(prof$parameter_values)))
})

test_that("get_profile uses the same profiled parameter as HAK_2025/profile.dat", {
  mpd <- extract.mpd(file = testmodel("HAK_2025/profile.log"), quiet = TRUE)
  prof <- get_profile(mpd)
  pars <- extract.parameters(file = testmodel("HAK_2025/profile.dat"), quiet = TRUE)

  param_name <- unique(prof$parameter)
  expect_equal(length(param_name), 1L)
  expect_true(param_name %in% colnames(pars))
})

test_that("get_profile parameter grid matches HAK_2025/profile.dat", {
  mpd <- extract.mpd(file = testmodel("HAK_2025/profile.log"), quiet = TRUE)
  prof <- get_profile(mpd)
  pars <- extract.parameters(file = testmodel("HAK_2025/profile.dat"), quiet = TRUE)

  param_name <- unique(prof$parameter)
  grid_from_get_profile <- sort(unique(prof$parameter_values))
  grid_from_profile_dat <- sort(as.numeric(pars[[param_name]]))

  expect_equal(length(grid_from_get_profile), nrow(pars))
  expect_equal(grid_from_get_profile, grid_from_profile_dat, tolerance = 1e-8)
})

test_that("get_profile supports named list input like other get_* accessors", {
  mpd <- extract.mpd(file = testmodel("HAK_2025/profile.log"), quiet = TRUE)
  model_list <- list(run_a = mpd, run_b = mpd)

  prof_list <- get_profile(model_list)
  prof_single <- get_profile(mpd)

  expect_true(is.data.frame(prof_list))
  expect_true("model_label" %in% names(prof_list))
  expect_equal(sort(unique(as.character(prof_list$model_label))), c("run_a", "run_b"))
  expect_equal(nrow(prof_list), 2L * nrow(prof_single))
})

test_that("get_profile works with aggregate_obs set to TRUE and FALSE", {
  mpd <- extract.mpd(file = testmodel("HAK_2025/profile.log"), quiet = TRUE)

  prof_agg_true <- get_profile(mpd, aggregate_obs = TRUE)
  prof_agg_false <- get_profile(mpd, aggregate_obs = FALSE)

  expect_true(is.data.frame(prof_agg_true))
  expect_true(is.data.frame(prof_agg_false))
  expect_true(nrow(prof_agg_true) > 0L)
  expect_true(nrow(prof_agg_false) > 0L)

  required_cols <- c("component", "parameter_values", "negative_loglikelihood", "parameter")
  expect_true(all(required_cols %in% names(prof_agg_true)))
  expect_true(all(required_cols %in% names(prof_agg_false)))
})
