#' @title reformat_default_labels
#' @description Reformat report labels generated by Casal2's default reporting.
#'   Labels with leading and trailing double-underscores (e.g. \code{__selectivities__})
#'   are trimmed to the inner text (e.g. \code{selectivities}).  When trimming
#'   would create a duplicate label the default-report label is suffixed with
#'   \code{_default}.
#' @author Casal2 Development Team
#' @param report_labels Character vector of Casal2 report labels.
#' @return Character vector of reformatted labels, same length as \code{report_labels}.
#' @export reformat_default_labels
#' @examples
#' \dontrun{
#' reformat_default_labels(c("header", "__selectivities__", "my_report"))
#' }
reformat_default_labels <- function(report_labels) {
  n <- nchar(report_labels)
  ## identify labels that both start and end with '__'
  default_ndx <- startsWith(report_labels, "__") & endsWith(report_labels, "__")
  new_labels <- report_labels
  ## strip the leading/trailing '__' from default labels
  new_labels[default_ndx] <- substring(report_labels[default_ndx], 3L, n[default_ndx] - 2L)
  ## resolve duplicates: if trimming created a collision with an original label,
  ## suffix every default-derived label that collides with '_default'
  non_default_names <- new_labels[!default_ndx]
  colliding <- default_ndx & (new_labels %in% non_default_names)
  if (any(colliding)) {
    new_labels[colliding] <- paste0(new_labels[colliding], "_default")
  }
  new_labels
}
