#' @title reformat_default_labels
#' @description Reformat report labels generated by Casal2's default reporting.
#'   Labels with leading and trailing double-underscores (e.g. \code{__selectivities__})
#'   are trimmed to the inner text (e.g. \code{selectivities}).  When trimming
#'   would create a duplicate label the default-report label is suffixed with
#'   \code{_default}.
#' @author Casal2 Development Team
#' @param report_labels Character vector of Casal2 report labels.
#' @return Character vector of reformatted labels, same length as \code{report_labels}.
#' @export reformat_default_labels
#' @examples
#' \dontrun{
#' reformat_default_labels(c("header", "__selectivities__", "my_report"))
#' }
reformat_default_labels <- function(report_labels) {
  n <- nchar(report_labels)
  ## identify labels that both start and end with '__'
  default_ndx <- startsWith(report_labels, "__") & endsWith(report_labels, "__")
  new_labels <- report_labels
  ## strip the leading/trailing '__' from default labels
  new_labels[default_ndx] <- substring(report_labels[default_ndx], 3L, n[default_ndx] - 2L)
  ## resolve duplicates: if trimming created a collision with an original label,
  ## suffix the default-derived label with '_default'
  dup_pos <- anyDuplicated(new_labels)
  if (dup_pos != 0L) {
    dup_val  <- new_labels[dup_pos]
    all_dups <- which(new_labels == dup_val)
    ## the original (non-default) label keeps its name; the default-derived one is renamed
    original_ndx <- all_dups[!default_ndx[all_dups]]
    default_dup  <- all_dups[default_ndx[all_dups]]
    if (length(default_dup) > 0L)
      new_labels[default_dup] <- paste0(new_labels[default_dup], "_default")
  }
  new_labels
}
